name: Run RapidAPI Football Odds

on:
  workflow_dispatch:
  push:
    paths:
      - main.py

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Reponu klonla
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kitabxanaları yüklə
      run: |
        pip install -r requirements.txt

    - name: Python skriptini işə sal
      run: python main.py
